- baseInfo:
    api_name: 商品详情
    url: /coupApply/cms/productDetail
    method: post
    header:
      Content-Type: application/json;charset=UTF-8
  testCase:
    - case_name: 获取商品详情
      json:
        pro_id: ${get_extract_data(goodsId)}
        page: 1
        size: 20
      validation:
        - contains: { 'error_code': '4000' }